= EOEPCA - Public Project Page

*_(Document Source for Authors)_*

This is the raw page source and build/publish system.

The published page can be found https://eoepca.github.io/[here].

The page is editable under link:src/docs/asciidoc[`src/docs/asciidoc`].

The document is authored in AsciiDoc and converted to HTML using https://github.com/asciidoctor/asciidoctor[Asciidoctor].

The output is automatically published via GitHub at the URL https://eoepca.github.io/ using the https://github.com/ajoberstar/gradle-git-publish[Gradle Git Publish plugin]. In order to authenticate to the EOEPCA git repository it is necessary to obtain a 'Personal Access Token' for your GitHub user, and make this available to the gradle build in the environment variable `GRGIT_USER`.

The page (source) is maintained in this repository (`eoepca.github.io`) under this sub-directory, and the rendered version (build output) is published back to the root of the master branch for public consumption, being careful not to destroy any of the sources, e.g. this directory.

Build::
The document is built by running...
```
$ ./generate.sh
```

Publish::
The document is published by running...
```
$ ./publish.sh
```

Related links::
* https://asciidoctor.org/[Asciidoctor Home Page]
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc syntax reference]
* https://github.com/asciidoctor/asciidoctor-gradle-plugin[Gradle Asciidoc Plugin]
